export const dummyUsers = [
    {
        id: '1',
        username: 'ibrahim',
        password: '123',
        profileImage: require('../assets/ibrahim.png'),
        followers: ['2', '3', '5'],
        following: ['2', '4'],
        about: 'aasfdfslşfmsdlkfmsdflşlksfnkldsşngdslkg',
    },
    {
        id: '2',
        username: 'ozer',
        password: '456',
        profileImage: require('../assets/ozer.jpg'),
        followers: ['1'],
        following: ['4', '3'],
        about: 'aasfdfslşfmsdlkfmsdflşlksfnkldsşngdslkg',
    },
    {
        id: '3',
        username: 'john',
        password: '789',
        profileImage: require('../assets/john.jpg'),
        followers: ['2', '5'],
        following: ['4', '1'],
        about: 'aasfdfslşfmsdlkfmsdflşlksfnkldsşngdslkg',
    },
    {
        id: '4',
        username: 'jane',
        password: '101112',
        profileImage: require('../assets/jane.jpeg'),
        followers: ['2', '3'],
        following: ['5', '1'],
        about: 'aasfdfslşfmsdlkfmsdflşlksfnkldsşngdslkg',
    },
    {
        id: '5',
        username: 'alice',
        password: '131415',
        profileImage: require('../assets/alice.jpeg'),
        followers: ['1', '2'],
        following: ['3'],
        about: 'aasfdfslşfmsdlkfmsdflşlksfnkldsşngdslkg',
    },
];
